2022-04-17 00:02:44,592 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-04-17 00:02:44,592 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\rodrigo\AppData\Local\Programs\Python\Python310\lib\site-packages\instabot\bot\bot.py
2022-04-17 00:02:44,593 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-04-17 00:02:44,785 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-04-17 00:02:45,003 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-04-17 00:02:45,208 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-04-17 00:02:45,395 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-04-17 00:02:47,962 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-04-17 00:02:47,962 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"The password you entered is incorrect. Please try again.","invalid_credentials":true,"error_title":"Incorrect password","buttons":[{"title":"OK","action":"dismiss"}],"status":"fail","error_type":"bad_password"}'
2022-04-17 00:02:47,962 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-04-17 00:02:47,963 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: The password you entered is incorrect. Please try again.
2022-04-17 00:02:47,963 - instabot version: 0.117.0 (api) - INFO - Error type: bad_password
2022-04-17 00:02:47,964 - instabot version: 0.117.0 (api) - ERROR - Failed to login go to instagram and change your password
2022-04-17 00:02:47,965 - instabot version: 0.117.0 (api) - INFO - Username or password is incorrect.
2022-04-17 00:02:47,968 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-04-17 00:02:47,970 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\rodrigo\AppData\Local\Programs\Python\Python310\lib\site-packages\instabot\bot\bot.py
2022-04-17 00:02:47,970 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-04-17 00:02:48,171 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2022-04-17 00:02:48,171 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-04-17 00:02:48,172 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-04-17 00:02:48,173 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2022-04-17 00:07:48,406 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2022-04-17 00:07:48,406 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-04-17 00:07:48,406 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-04-17 00:07:48,407 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 10 minutes.
